import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { startWorkshop, usePrepared, activeSeries, saveWorkshop, checkWorkshop } from '../miris/workshop.mjs';
const fixtures=JSON.parse(await readFile(new URL('../miris/fixtures.json',import.meta.url),'utf8'));
const empty={track:'',specimens:[],concept:'',zipReady:false,hatchedAt:0};
const started={...empty,...startWorkshop(empty,fixtures,1234)};
assert.equal(started.flowVersion,3);assert.equal(started.workshopStartedAt,1234);
assert.equal(activeSeries(started).specimens.length,6);
assert.equal(new Set(activeSeries(started).specimens.map(s=>s.uuid)).size,6);
assert.equal(activeSeries(started).viewerKey,fixtures.viewerKey);
assert.equal(started.hatchedAt,0);assert.equal(started.zipReady,false);
const paid={...started,concept:'my creature',specimens:[{id:'01',uuid:'mine',glb:'paid.glb'}],hatchedAt:123,zipReady:false,previewSeries:null};
const kept={...paid,...startWorkshop(paid,fixtures,777)};
assert.equal(kept.specimens[0].uuid,'mine');assert.equal(kept.specimens[0].glb,'paid.glb');
const fallback={...paid,...usePrepared(paid,fixtures)};
assert.equal(fallback.specimens[0].glb,'paid.glb');assert.equal(fallback.hatchedAt,123);
assert.equal(activeSeries(fallback).specimens.length,6);
assert.throws(()=>saveWorkshop(started,'design',{title:'x',rotationSpeed:99,fov:55}));
assert.throws(()=>saveWorkshop(started,'publish',{url:'javascript:alert(1)',opened:true}));
assert.throws(()=>saveWorkshop(started,'attribution','generation'));
assert.equal(checkWorkshop(started,'publish')!==null,true);
const pub={...started,...saveWorkshop(started,'publish',{url:'https://example.com/lab',opened:true})};
assert.equal(checkWorkshop(pub,'publish'),null);
const designed={...started,...saveWorkshop(started,'design',{title:'Pelagic archive',rotationSpeed:0.04,fov:70})};
assert.equal(designed.labDesign.title,'Pelagic archive');
const story={...started,...saveWorkshop(started,'story',{index:0,name:'My observer',notes:'My own observation of this organism.'})};
assert.equal(activeSeries(story).specimens[0].dossier.name,'My observer');
assert.equal(started.previewSeries.specimens[0].dossier.name,fixtures.stages[0].dossier.name);
assert.equal(checkWorkshop(story,'story'),null);
assert.equal(checkWorkshop(started,'reflection')!==null,true);
assert.throws(()=>usePrepared(empty,{stages:[],viewerKey:''}));
console.log('PASS: prepared initialization, preservation, in-flight fallback, immutable curation, validation and completion gates');
const {publishSnapshot,chooseSource,escapeMarkup}=await import('../miris/workshop.mjs');
const snapshot=publishSnapshot({...fallback,workshopAnswers:{reflection:{peer:'private workshop feedback'}}});
assert.equal(snapshot.specimens[0].uuid,fixtures.stages[0].uuid);
assert.equal('workshopAnswers' in snapshot,false);assert.equal('glb' in snapshot.specimens[0],false);
const generating={...started,...chooseSource(started,'generate',fixtures)};
assert.equal(generating.workshopPath,'generate');assert.deepEqual(generating.previewSeries,started.previewSeries);
assert.equal(escapeMarkup('<img src=x onerror=alert(1)>'),'&lt;img src=x onerror=alert(1)&gt;');
assert.equal(checkWorkshop({...started,...saveWorkshop(started,'reflection',{peer:'I opened it on my other laptop.',miris:'Miris streams the specimen assets.',next:'A catalogue of scanned sculpture.'})},'reflection')!==null,true);
console.log('PASS: publication selects the displayed source, excludes private progress, escapes attendee HTML and requires a published link before finish');

assert.deepEqual(publishSnapshot(story).specimens[0].dossier, activeSeries(story).specimens[0].dossier);
const migrating={...empty,viewerKey:'existing-key',specimens:[{id:'01',uuid:'existing-id',glb:'paid.glb'}]};
assert.equal(startWorkshop(migrating,fixtures).previewSeries,null);
assert.equal(activeSeries({...empty,...startWorkshop({...empty,specimens:[{uuid:'missing-key'}]},fixtures)}).viewerKey,fixtures.viewerKey);
assert.throws(()=>saveWorkshop(started,'publish',{url:'http://localhost:3000',opened:true}));
assert.throws(()=>saveWorkshop(started,'publish',{url:'https://example.com',opened:false}));
